import type { SupportedLanguage } from '@/lib/languages';

const copy: Record<SupportedLanguage, { title: string; text: string }> = {
  en: { title: 'Measurement', text: 'With your choices, Vercel Web Analytics and Speed Insights measure audience and performance. Optional Neon and PostHog product measurement sends predefined TCG events, normalized page views, and limited error/performance context. An authenticated technical account ID may continue an anonymous PostHog session; email, names and secrets are excluded. Replay is consent-gated, sampled and masked. You can withdraw at any time.' },
  fr: { title: 'Mesure', text: 'Selon vos choix, Vercel Web Analytics et Speed Insights mesurent audience et performance. La mesure produit Neon et PostHog, facultative, envoie des événements TCG prédéfinis, des vues normalisées et un contexte limité d’erreur/performance. Un identifiant technique de compte peut prolonger une session PostHog anonyme ; e-mail, noms et secrets sont exclus. Le replay est soumis au consentement, échantillonné et masqué. Vous pouvez retirer votre choix à tout moment.' },
  es: { title: 'Medición', text: 'Según tus elecciones, Vercel Web Analytics y Speed Insights miden audiencia y rendimiento. La medición opcional de producto de Neon y PostHog envía eventos TCG predefinidos, vistas normalizadas y contexto limitado de errores y rendimiento. Un identificador técnico de cuenta puede continuar una sesión anónima de PostHog; se excluyen correos, nombres y secretos. La reproducción requiere consentimiento, se muestrea y se enmascara. Puedes retirar tu elección en cualquier momento.' },
  de: { title: 'Messung', text: 'Je nach Auswahl messen Vercel Web Analytics und Speed Insights Reichweite und Leistung. Die optionale Neon- und PostHog-Produktmessung sendet vordefinierte TCG-Ereignisse, normalisierte Seitenaufrufe sowie begrenzte Fehler- und Leistungsdaten. Eine technische Konto-ID kann eine anonyme PostHog-Sitzung fortsetzen; E-Mail, Namen und Geheimnisse werden ausgeschlossen. Replay ist zustimmungsabhängig, stichprobenbasiert und maskiert. Die Auswahl kann jederzeit widerrufen werden.' },
  it: { title: 'Misurazione', text: 'In base alle tue scelte, Vercel Web Analytics e Speed Insights misurano pubblico e prestazioni. La misurazione prodotto facoltativa di Neon e PostHog invia eventi TCG predefiniti, viste normalizzate e contesto limitato su errori e prestazioni. Un identificatore tecnico dell’account può continuare una sessione PostHog anonima; email, nomi e segreti sono esclusi. Il replay richiede il consenso, è campionato e mascherato. Puoi revocare la scelta in qualsiasi momento.' },
  ja: { title: '計測', text: '選択に応じて、Vercel Web Analytics と Speed Insights が利用状況と性能を計測します。任意の Neon と PostHog の製品計測は、定義済みの TCG イベント、正規化したページビュー、限定的なエラーと性能のコンテキストを送信します。技術的なアカウント ID が匿名の PostHog セッションを継続する場合がありますが、メール、氏名、秘密情報は除外します。リプレイは同意後のみ、サンプリングとマスキングを行います。いつでも撤回できます。' },
  ko: { title: '측정', text: '선택에 따라 Vercel Web Analytics와 Speed Insights가 이용 현황과 성능을 측정합니다. 선택 사항인 Neon 및 PostHog 제품 측정은 사전 정의된 TCG 이벤트, 정규화된 페이지 조회, 제한된 오류 및 성능 맥락을 전송합니다. 기술적 계정 ID가 익명 PostHog 세션을 이어갈 수 있지만 이메일, 이름과 비밀 정보는 제외됩니다. 리플레이는 동의 후에만 샘플링하고 마스킹합니다. 언제든 철회할 수 있습니다.' },
  zh: { title: '测量', text: '根据您的选择，Vercel Web Analytics 和 Speed Insights 用于测量受众与性能。可选的 Neon 和 PostHog 产品测量会发送预定义的 TCG 事件、规范化页面浏览以及有限的错误和性能上下文。技术账户 ID 可能继续匿名 PostHog 会话；电子邮件、姓名和秘密信息会被排除。回放仅在获得同意后启用，并进行采样和遮罩。您可以随时撤回选择。' },
};

export function MeasurementNotice({ lang }: { lang: SupportedLanguage }) { const item = copy[lang]; return <section className="mt-8 rounded-lg border border-foreground/10 p-5"><h2 className="text-lg font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-foreground/80">{item.text}</p></section>; }
