import type { SupportedLanguage } from '@/lib/languages';

type GuideCopy = {
  pull: { title: string; description: string; methodTitle: string; method: string; evidenceTitle: string; evidence: string; limitTitle: string; limit: string; unavailable: string };
  value: { title: string; description: string; methodTitle: string; method: string; evidenceTitle: string; evidence: string; limitTitle: string; limit: string; unavailable: string };
  links: { pull: string; value: string; catalog: string };
  status: string;
};

export const boosterGuidesTranslations: Record<SupportedLanguage, GuideCopy> = {
  en: {
    pull: { title: 'Pokémon TCG booster pull rates', description: 'Understand observed rarity frequencies for a specific set, region and booster type.', methodTitle: 'How a rate is calculated', method: 'For each rarity, divide the number of cards observed by the number of packs opened. The result is observed copies per pack, not the probability that a pack contains at least one card of that rarity.', evidenceTitle: 'What a sample must show', evidence: 'A usable sample names its source, set, region, booster type, opening dates, pack count, cards per pack and counts for every observed rarity. Rarity totals must match the recorded card variants.', limitTitle: 'How to read the result', limit: 'Openings vary. A sample describes what was observed, not a guaranteed result for your next pack. Without pack-level hit records, aggregated card counts cannot establish the chance of at least one hit.', unavailable: 'No validated opening sample is published yet. Numeric pull rates are unavailable.' },
    value: { title: 'Pokémon TCG booster expected value', description: 'Learn how observed openings and matching EUR prices can estimate a booster’s gross card value.', methodTitle: 'How value is estimated', method: 'Multiply each observed card-variant count by its matching Cardmarket EUR price. Add those amounts and divide by packs opened. Compare that gross card value with a matching booster price.', evidenceTitle: 'What prices must cover', evidence: 'The opening sample and price snapshot must match the set, region and booster type. Every observed card variant needs a corresponding Cardmarket EUR quote, and the booster price needs its own source.', limitTitle: 'An estimate, not a return', limit: 'Market prices move. Condition, selling fees, shipping, taxes and unsold cards can change the amount received. An average from past openings does not promise a profitable pack.', unavailable: 'No validated opening sample with complete matching EUR Cardmarket prices is published yet. Numeric expected value is unavailable.' },
    links: { pull: 'Pull rates', value: 'Booster value', catalog: 'TCG catalog' }, status: 'Data status',
  },
  fr: {
    pull: { title: 'Fréquences de tirage des boosters Pokémon', description: 'Comprendre les fréquences de rareté observées pour une extension, une région et un type de booster précis.', methodTitle: 'Calcul de la fréquence', method: 'Pour chaque rareté, on divise le nombre de cartes observées par le nombre de boosters ouverts. Le résultat indique des exemplaires observés par booster, pas la probabilité qu’un booster contienne au moins une carte de cette rareté.', evidenceTitle: 'Données nécessaires', evidence: 'Un échantillon exploitable précise sa source, son extension, sa région, son type de booster, ses dates, le nombre de boosters, les cartes par booster et les effectifs de chaque rareté. Les totaux doivent correspondre aux variantes recensées.', limitTitle: 'Interpréter le résultat', limit: 'Les ouvertures varient. Un échantillon décrit des observations et ne garantit rien pour le prochain booster. Sans relevé par booster, les totaux ne donnent pas la probabilité d’au moins un tirage.', unavailable: 'Aucun échantillon d’ouvertures validé n’est publié. Les fréquences chiffrées sont indisponibles.' },
    value: { title: 'Valeur attendue d’un booster Pokémon', description: 'Comprendre comment les ouvertures observées et les prix en euros permettent d’estimer la valeur brute des cartes.', methodTitle: 'Calcul de la valeur', method: 'On multiplie l’effectif de chaque variante observée par son prix Cardmarket en euros, puis on divise la somme par le nombre de boosters ouverts. On compare cette valeur brute au prix du booster correspondant.', evidenceTitle: 'Couverture des prix', evidence: 'L’échantillon et les prix doivent concerner la même extension, région et type de booster. Chaque variante observée doit avoir un prix Cardmarket en euros, et le prix du booster doit être sourcé.', limitTitle: 'Une estimation, pas un gain', limit: 'Les prix changent. L’état, les frais de vente, l’expédition, les taxes et les invendus modifient le montant reçu. Une moyenne passée ne garantit aucun bénéfice.', unavailable: 'Aucun échantillon validé avec une couverture complète des prix Cardmarket en euros n’est publié. La valeur chiffrée est indisponible.' },
    links: { pull: 'Fréquences de tirage', value: 'Valeur des boosters', catalog: 'Catalogue JCC' }, status: 'État des données',
  },
  es: {
    pull: { title: 'Frecuencias de cartas en sobres Pokémon', description: 'Comprende las frecuencias de rareza observadas para una colección, región y tipo de sobre concretos.', methodTitle: 'Cómo se calcula', method: 'Para cada rareza, se divide el número de cartas observadas entre los sobres abiertos. El resultado son copias observadas por sobre, no la probabilidad de encontrar al menos una carta de esa rareza.', evidenceTitle: 'Datos necesarios', evidence: 'La muestra debe indicar fuente, colección, región, tipo de sobre, fechas, número de sobres, cartas por sobre y recuentos de cada rareza. Los totales deben coincidir con las variantes registradas.', limitTitle: 'Cómo interpretarlo', limit: 'Las aperturas varían. La muestra describe observaciones, sin garantizar el próximo sobre. Sin registros por sobre, los recuentos no indican la probabilidad de obtener al menos un acierto.', unavailable: 'Todavía no hay muestras de aperturas validadas. Las frecuencias numéricas no están disponibles.' },
    value: { title: 'Valor esperado de un sobre Pokémon', description: 'Cómo las aperturas observadas y los precios en EUR permiten estimar el valor bruto de las cartas.', methodTitle: 'Cómo se estima', method: 'Multiplica el recuento de cada variante observada por su precio Cardmarket en EUR. Suma los importes y divide entre los sobres abiertos. Compara el valor bruto con el precio del sobre correspondiente.', evidenceTitle: 'Cobertura de precios', evidence: 'Muestra y precios deben coincidir en colección, región y tipo de sobre. Cada variante observada necesita un precio Cardmarket en EUR y el precio del sobre debe tener una fuente.', limitTitle: 'Estimación, no ganancia', limit: 'Los precios cambian. Estado, comisiones, envío, impuestos y cartas sin vender alteran el importe recibido. Una media histórica no garantiza beneficios.', unavailable: 'Todavía no hay una muestra validada con precios Cardmarket en EUR para todas las variantes. El valor numérico no está disponible.' },
    links: { pull: 'Frecuencias de sobres', value: 'Valor del sobre', catalog: 'Catálogo JCC' }, status: 'Estado de los datos',
  },
  de: {
    pull: { title: 'Ziehraten von Pokémon-Boostern', description: 'Beobachtete Seltenheitshäufigkeiten für ein bestimmtes Set, eine Region und einen Boostertyp verstehen.', methodTitle: 'Berechnung', method: 'Für jede Seltenheit wird die beobachtete Kartenzahl durch die Zahl geöffneter Booster geteilt. Das ergibt Exemplare pro Booster, nicht die Wahrscheinlichkeit für mindestens eine solche Karte.', evidenceTitle: 'Erforderliche Daten', evidence: 'Eine Stichprobe nennt Quelle, Set, Region, Boostertyp, Zeitraum, Boosterzahl, Karten pro Booster und alle Seltenheitszahlen. Die Summen müssen mit den erfassten Varianten übereinstimmen.', limitTitle: 'Ergebnis einordnen', limit: 'Öffnungen schwanken. Die Stichprobe beschreibt Beobachtungen und garantiert kein Ergebnis für den nächsten Booster. Ohne Daten je Booster lässt sich die Chance auf mindestens einen Treffer nicht bestimmen.', unavailable: 'Es liegt noch keine validierte Öffnungsstichprobe vor. Zahlen zu Ziehraten sind nicht verfügbar.' },
    value: { title: 'Erwartungswert eines Pokémon-Boosters', description: 'Wie Öffnungsdaten und passende EUR-Preise den Bruttowert der Karten schätzen.', methodTitle: 'Berechnung des Werts', method: 'Die Zahl jeder beobachteten Kartenvariante wird mit ihrem Cardmarket-Preis in EUR multipliziert. Die Summe wird durch die geöffneten Booster geteilt und mit dem passenden Boosterpreis verglichen.', evidenceTitle: 'Preisabdeckung', evidence: 'Stichprobe und Preise müssen zu Set, Region und Boostertyp passen. Für jede beobachtete Variante ist ein Cardmarket-Preis in EUR nötig; auch der Boosterpreis braucht eine Quelle.', limitTitle: 'Schätzung statt Gewinn', limit: 'Marktpreise ändern sich. Zustand, Verkaufsgebühren, Versand, Steuern und unverkaufte Karten beeinflussen den Erlös. Ein historischer Durchschnitt garantiert keinen Gewinn.', unavailable: 'Eine validierte Stichprobe mit vollständigen Cardmarket-Preisen in EUR liegt noch nicht vor. Ein Zahlenwert ist nicht verfügbar.' },
    links: { pull: 'Ziehraten', value: 'Boosterwert', catalog: 'TCG-Katalog' }, status: 'Datenstatus',
  },
  it: {
    pull: { title: 'Frequenze di estrazione dei booster Pokémon', description: 'Capire le frequenze osservate delle rarità per espansione, regione e tipo di booster.', methodTitle: 'Come si calcola', method: 'Per ogni rarità, dividi le carte osservate per i booster aperti. Il risultato indica copie osservate per booster, non la probabilità di trovare almeno una carta di quella rarità.', evidenceTitle: 'Dati necessari', evidence: 'Il campione indica fonte, espansione, regione, tipo di booster, periodo, numero di booster, carte per booster e conteggi per rarità. I totali devono corrispondere alle varianti registrate.', limitTitle: 'Come leggerlo', limit: 'Le aperture variano. Il campione descrive ciò che è stato osservato, senza garantire il prossimo booster. Senza dati per singolo booster non si può stimare la probabilità di almeno un ritrovamento.', unavailable: 'Non è ancora pubblicato un campione di aperture convalidato. Le frequenze numeriche non sono disponibili.' },
    value: { title: 'Valore atteso di un booster Pokémon', description: 'Come aperture osservate e prezzi in EUR stimano il valore lordo delle carte.', methodTitle: 'Come si stima', method: 'Moltiplica il numero di ogni variante osservata per il relativo prezzo Cardmarket in EUR. Somma e dividi per i booster aperti, poi confronta il valore lordo con il prezzo del booster corrispondente.', evidenceTitle: 'Copertura dei prezzi', evidence: 'Campione e prezzi devono corrispondere per espansione, regione e tipo di booster. Ogni variante osservata richiede una quotazione Cardmarket in EUR; anche il prezzo del booster deve avere una fonte.', limitTitle: 'Stima, non profitto', limit: 'I prezzi cambiano. Condizioni, commissioni, spedizione, imposte e carte invendute incidono sul ricavo. Una media passata non garantisce un profitto.', unavailable: 'Non è ancora pubblicato un campione convalidato con prezzi Cardmarket in EUR per tutte le varianti. Il valore numerico non è disponibile.' },
    links: { pull: 'Frequenze', value: 'Valore booster', catalog: 'Catalogo GCC' }, status: 'Stato dei dati',
  },
  ja: {
    pull: { title: 'ポケモンカードの拡張パック封入率', description: 'セット、地域、パックの種類ごとに観測されたレアリティの頻度を説明します。', methodTitle: '頻度の計算方法', method: '各レアリティの観測枚数を開封パック数で割ります。これは1パック当たりの観測枚数であり、そのレアリティが1枚以上出る確率ではありません。', evidenceTitle: '必要な記録', evidence: '出典、セット、地域、パックの種類、開封期間、パック数、1パックの枚数、各レアリティの枚数が必要です。合計は記録されたカードの種類別枚数と一致しなければなりません。', limitTitle: '結果の読み方', limit: '開封結果にはばらつきがあります。過去の観測は次のパックの結果を保証しません。パックごとの記録がなければ、1枚以上出る確率は求められません。', unavailable: '検証済みの開封サンプルはまだ公開されていません。数値の封入率は表示できません。' },
    value: { title: 'ポケモンカード拡張パックの期待値', description: '開封記録と対応するユーロ価格からカードの額面上の平均価値を推定する方法を説明します。', methodTitle: '価値の推定方法', method: '観測された各カード仕様の枚数に、対応するCardmarketのユーロ価格を掛けます。合計を開封パック数で割り、対応するパック価格と比較します。', evidenceTitle: '価格の網羅性', evidence: '開封記録と価格は同じセット、地域、パック種類に対応する必要があります。観測された全カード仕様のCardmarketユーロ価格と、出典付きのパック価格が必要です。', limitTitle: '利益の保証ではありません', limit: '相場は変動します。状態、販売手数料、送料、税金、売れ残りによって実際の受取額は変わります。過去の平均値は利益を保証しません。', unavailable: '全仕様のCardmarketユーロ価格を備えた検証済みサンプルはまだありません。数値の期待値は表示できません。' },
    links: { pull: '封入率', value: 'パックの価値', catalog: 'カード図鑑' }, status: 'データの状況',
  },
  ko: {
    pull: { title: '포켓몬 카드 부스터팩 등장 빈도', description: '세트, 지역, 부스터 종류별로 관찰된 희귀도 빈도를 설명합니다.', methodTitle: '빈도 계산', method: '희귀도별 관찰 카드 수를 개봉한 팩 수로 나눕니다. 이는 팩당 관찰 매수이며, 해당 희귀도 카드가 한 장 이상 나올 확률은 아닙니다.', evidenceTitle: '필요한 표본', evidence: '출처, 세트, 지역, 부스터 종류, 개봉 기간, 팩 수, 팩당 카드 수, 희귀도별 수량이 필요합니다. 합계는 기록된 카드 변형별 수량과 일치해야 합니다.', limitTitle: '결과 해석', limit: '개봉 결과는 달라집니다. 표본은 과거 관찰을 보여 줄 뿐 다음 팩의 결과를 보장하지 않습니다. 팩별 기록이 없으면 한 장 이상 나올 확률을 알 수 없습니다.', unavailable: '검증된 개봉 표본이 아직 공개되지 않았습니다. 수치 등장 빈도는 제공되지 않습니다.' },
    value: { title: '포켓몬 카드 부스터팩 기대 가치', description: '개봉 기록과 해당 유로 가격으로 카드의 총가치를 추정하는 방법입니다.', methodTitle: '가치 추정', method: '관찰된 각 카드 변형 수량에 해당 Cardmarket 유로 가격을 곱합니다. 합계를 개봉 팩 수로 나눈 뒤 해당 팩 가격과 비교합니다.', evidenceTitle: '가격 적용 범위', evidence: '표본과 가격의 세트, 지역, 부스터 종류가 같아야 합니다. 관찰된 모든 카드 변형의 Cardmarket 유로 가격과 출처가 있는 팩 가격이 필요합니다.', limitTitle: '수익 보장이 아닙니다', limit: '시세는 변합니다. 상태, 판매 수수료, 배송비, 세금, 팔리지 않은 카드는 실제 수령액에 영향을 줍니다. 과거 평균은 수익을 보장하지 않습니다.', unavailable: '모든 카드 변형의 Cardmarket 유로 가격을 갖춘 검증된 표본이 아직 없습니다. 수치 기대 가치는 제공되지 않습니다.' },
    links: { pull: '등장 빈도', value: '부스터 가치', catalog: '카드 목록' }, status: '데이터 상태',
  },
  zh: {
    pull: { title: '宝可梦卡牌补充包抽取频率', description: '了解特定系列、地区和补充包类型中观察到的稀有度频率。', methodTitle: '频率如何计算', method: '将各稀有度的观察卡牌数除以开包数。结果是每包观察到的卡牌数量，不代表每包至少出现一张该稀有度卡牌的概率。', evidenceTitle: '样本需要什么', evidence: '样本须注明来源、系列、地区、补充包类型、开包日期、包数、每包卡数和各稀有度数量。总数须与记录的卡牌版本数量一致。', limitTitle: '如何理解结果', limit: '开包结果存在波动。样本仅描述已观察结果，不保证下一包的内容。缺少逐包记录时，不能计算至少抽中一张的概率。', unavailable: '尚未公布经过验证的开包样本，因此无法提供数值抽取频率。' },
    value: { title: '宝可梦卡牌补充包期望价值', description: '了解如何用开包记录和对应的欧元价格估算卡牌总价值。', methodTitle: '价值如何估算', method: '将每种已观察卡牌版本的数量乘以对应的 Cardmarket 欧元价格，求和后除以开包数，再与对应补充包价格比较。', evidenceTitle: '价格覆盖要求', evidence: '样本和价格须对应相同的系列、地区和补充包类型。每种已观察卡牌版本都须有 Cardmarket 欧元报价，补充包价格也须注明来源。', limitTitle: '估算不保证盈利', limit: '市场价格会变动。品相、销售费用、运费、税费和未售出卡牌都会影响实际收入。历史平均值不保证盈利。', unavailable: '尚无覆盖全部卡牌版本 Cardmarket 欧元价格的验证样本，因此无法提供数值期望价值。' },
    links: { pull: '抽取频率', value: '补充包价值', catalog: '卡牌目录' }, status: '数据状态',
  },
};
