import type { SealedReleaseV1 } from '@/lib/tcg-release-calendar';

const POKECARDEX_2026_SOURCE = {
  publisher: 'PokéCardex',
  url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
  verifiedAt: '2026-09-30',
} as const;

/**
 * French-market editorial snapshot, version 1. Review each source and status
 * before updating; a date is never inferred from a marketplace listing.
 * Cardmarket IDs below were checked against the public catalogue on 2026-09-30.
 * Combined products and ambiguous variants deliberately stay unlinked.
 */
export const SEALED_RELEASES_V1 = [
  {
    id: 'destinees-de-paldea',
    titleFr: 'Écarlate et Violet – Destinées de Paldea',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2024-01-26' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actus-pokemon/les-pokemon-chromatiques-brillent-avec-mimiqui-gardevoir-ex-dracaufeu-ex-et-dautres-dans-ecarlate-et-violet-destinees-de-paldea',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'forces-temporelles',
    titleFr: 'Écarlate et Violet – Forces Temporelles',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'quarter', year: 2024, quarter: 1 },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/galerie-produits/coffret-dresseur-delite-ecarlate-et-violet-forces-temporelles',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mascarade-crepusculaire',
    titleFr: 'Écarlate et Violet – Mascarade Crépusculaire',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2024-05-24' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/admirez-les-nouvelles-cartes-de-lextension-ecarlate-et-violet-mascarade-crepusculaire-du-jcc-pokemon',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'fable-nebuleuse',
    titleFr: 'Écarlate et Violet – Fable Nébuleuse',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2024-08-02' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/nouvel-apercu-des-cartes-de-lextension-ecarlate-et-violet-fable-nebuleuse',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'couronne-stellaire',
    titleFr: 'Écarlate et Violet – Couronne Stellaire',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2024-09-13' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/obtenez-le-boitier-strategies-et-combats-ecarlate-et-violet-couronne-stellaire-en-avance',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'etincelles-deferlantes',
    titleFr: 'Écarlate et Violet – Étincelles Déferlantes',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2024-11-08' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/decouvrez-de-nouvelles-cartes-de-lextension-ecarlate-et-violet-etincelles-deferlantes-du-jcc-pokemon',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'evolutions-prismatiques',
    titleFr: 'Écarlate et Violet – Évolutions Prismatiques',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-01-17' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'aventures-ensemble',
    titleFr: 'Écarlate et Violet – Aventures Ensemble',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-03-28' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'rivalites-destinees',
    titleFr: 'Écarlate et Violet – Rivalités Destinées',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-05-30' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'foudre-noire',
    titleFr: 'Écarlate et Violet – Foudre Noire',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-07-18' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'flamme-blanche',
    titleFr: 'Écarlate et Violet – Flamme Blanche',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-07-18' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution',
    titleFr: 'Méga-Évolution',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-10-10' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution-flammes-fantasmagoriques',
    titleFr: 'Méga-Évolution – Flammes Fantasmagoriques',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2025-11-14' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution-heros-transcendants',
    titleFr: 'Méga-Évolution – Héros Transcendants',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-01-30' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/jcc-pokemon/extensions-jeu-cartes-a-collectionner',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution-equilibre-parfait',
    titleFr: 'Méga-Évolution – Équilibre Parfait',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-03-27' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/retablissez-lordre-dans-le-jcc-pokemon',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution-chaos-ascendant',
    titleFr: 'Méga-Évolution – Chaos Ascendant',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-05-22' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/obtenez-un-boitier-strategies-et-combats-mega-evolution-chaos-ascendant-du-jcc-pokemon-en-avant-premiere',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution-nuit-noire',
    titleFr: 'Méga-Évolution – Nuit Noire',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-07-17' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/lextension-mega-evolution-nuit-noire-du-jcc-pokemon-est-a-present-disponible-dans-le-jcc-pokemon-live',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'pokemon-30th-anniversary-expansion',
    titleFr: '30ᵉ Anniversaire',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-09-16' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/lextension-30-anniversaire-du-jcc-pokemon-est-disponible',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mega-evolution-regne-delta',
    titleFr: 'Méga-Évolution – Règne Delta',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/lextension-mega-evolution-regne-delta-du-jcc-pokemon-arrive-le-6-novembre-2026',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-autocollant-30e',
    titleFr: 'JCC Pokémon : Collection autocollant réajustable 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-13' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'blister-2-boosters-30e',
    titleFr: 'JCC Pokémon : blister de 2 boosters 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-ko-30e',
    titleFr: 'JCC Pokémon : Collection K.O. 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 895559,
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-poster-30e',
    titleFr: 'JCC Pokémon : Collection poster 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 895553,
    window: { precision: 'day', date: '2026-09-16' },
    status: 'released',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
    retailPriceCents: 2799,
  },
  {
    id: 'coffrets-nymphali-amphinobi-30e',
    titleFr: 'JCC Pokémon : Coffret 30ᵉ Anniversaire – Nymphali-ex et Coffret 30ᵉ Anniversaire – Amphinobi-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-09-16' },
    status: 'released',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
    retailPriceCents: 2599,
  },
  {
    id: 'coffret-dresseur-elite-30e',
    titleFr: 'JCC Pokémon : Coffret Dresseur d’élite 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 895551,
    window: { precision: 'day', date: '2026-09-16' },
    status: 'released',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
    retailPriceCents: 5599,
  },
  {
    id: 'collection-premium-metamorph-30e',
    titleFr: 'JCC Pokémon : Collection Premium Métamorph 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 895574,
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'collection-ultra-premium-journee-soiree-30e',
    titleFr: 'JCC Pokémon : Collection Ultra-Premium 30ᵉ Anniversaire – Journée et Soirée',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'collection-figurine-mew-mewtwo-30e',
    titleFr: 'JCC Pokémon : Collection avec figurine 30ᵉ Anniversaire – Mew et Mewtwo',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'collection-classeur-30e',
    titleFr: 'JCC Pokémon : Collection classeur 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 895560,
    window: { precision: 'day', date: '2026-10-23' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
    retailPriceCents: 4599,
  },
  {
    id: 'lot-boosters-30e',
    titleFr: 'JCC Pokémon : lot de boosters 30ᵉ Anniversaire du JCC Pokémon',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 895561,
    window: { precision: 'day', date: '2026-10-02' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'mini-boites-30e',
    titleFr: 'JCC Pokémon : Mini-boîtes 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-10-02' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
  },
  {
    id: 'decks-combat-mentali-noctali-30e',
    titleFr: 'JCC Pokémon : Deck Combat 30ᵉ Anniversaire – Mentali-ex et Deck Combat 30ᵉ Anniversaire – Noctali-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-10-30' },
    status: 'announced',
    source: {
      publisher: 'PokéCardex',
      url: 'https://www.pokecardex.com/forums/viewtopic.php?t=49894',
      verifiedAt: '2026-09-30',
    },
    retailPriceCents: 2499,
  },
  {
    id: 'duopack-raikou-2026',
    titleFr: 'Pack 2 boosters janvier 2026 – Duopack Raikou',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-01-02' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1199,
  },
  {
    id: 'pack-journee-pokemon-2026',
    titleFr: 'Pack Collection Journée Pokémon 2026',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-01-30' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1999,
  },
  {
    id: 'duopack-heros-transcendants',
    titleFr: 'Pack 2 boosters Méga-Évolution – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-01-30' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1299,
  },
  {
    id: 'tripack-heros-transcendants',
    titleFr: 'Pack 3 boosters Méga-Évolution – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-01-30' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1999,
  },
  {
    id: 'etb-heros-transcendants',
    titleFr: 'Coffret Dresseur d’élite Méga-Évolution – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 860574,
    window: { precision: 'day', date: '2026-02-20' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 5599,
  },
  {
    id: 'mini-boites-heros-transcendants',
    titleFr: 'Mini-boîtes Méga-Évolution – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-02-20' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1199,
  },
  {
    id: 'pokebox-mega-dracaufeu',
    titleFr: 'Boîte Méga-Dracaufeu',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-02-20' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 2599,
  },
  {
    id: 'collection-premiers-partenaires-heroes-transcendants',
    titleFr: 'Coffret Collection avec pin’s Deluxe Premiers Partenaires – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 864106,
    window: { precision: 'day', date: '2026-03-20' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3299,
  },
  {
    id: 'poster-premium-heros-transcendants',
    titleFr: 'Coffret Collection poster Premium – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-03-20' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 5999,
  },
  {
    id: 'duopack-mars-2026',
    titleFr: 'Pack 2 boosters mars 2026 – Duopack Mystherbe, Ortide et Rafflesia',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-03-06' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1299,
  },
  {
    id: 'prerelease-equilibre-parfait',
    titleFr: 'Boîtier Stratégies et Combats – Équilibre Parfait',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 865397,
    window: { precision: 'day', date: '2026-03-14' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3000,
  },
  {
    id: 'etb-equilibre-parfait',
    titleFr: 'Coffret Dresseur d’élite Méga-Évolution – Équilibre Parfait',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 865406,
    window: { precision: 'day', date: '2026-03-27' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 5599,
  },
  {
    id: 'bundle-equilibre-parfait',
    titleFr: 'Lot de boosters Méga-Évolution – Équilibre Parfait',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 865404,
    window: { precision: 'day', date: '2026-03-27' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3599,
  },
  {
    id: 'coffret-collection-heros-transcendants',
    titleFr: 'Coffret Méga-Évolution – Héros Transcendants – Méga-Méganium-ex, Méga-Roitiflam-ex et Méga-Aligatueur-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-04-24' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 2599,
  },
  {
    id: 'bundle-heros-transcendants',
    titleFr: 'Lot de boosters Méga-Évolution – Héros Transcendants',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 860578,
    window: { precision: 'day', date: '2026-04-24' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3599,
  },
  {
    id: 'premium-mega-zygarde',
    titleFr: 'Coffret Collection Premium Méga-Zygarde-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-05-01' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 4999,
  },
  {
    id: 'prerelease-chaos-ascendant',
    titleFr: 'Boîtier Stratégies et Combats – Chaos Ascendant',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 877282,
    window: { precision: 'day', date: '2026-05-09' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3000,
  },
  {
    id: 'tripack-chaos-ascendant',
    titleFr: 'Pack 3 boosters Méga-Évolution – Chaos Ascendant',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-05-22' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1799,
  },
  {
    id: 'etb-chaos-ascendant',
    titleFr: 'Coffret Dresseur d’élite Méga-Évolution – Chaos Ascendant',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 877294,
    window: { precision: 'day', date: '2026-05-22' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 5599,
  },
  {
    id: 'bundle-chaos-ascendant',
    titleFr: 'Lot de boosters Méga-Évolution – Chaos Ascendant',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 877284,
    window: { precision: 'day', date: '2026-05-22' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3599,
  },
  {
    id: 'deck-combat-ligue-mega-lucario',
    titleFr: 'Deck Combat de Ligue Méga-Lucario-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-05-22' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3499,
  },
  {
    id: 'pokebox-mega-clair-de-lune',
    titleFr: 'Boîte Méga Clair de Lune – Méga-Mélodelfe ou Méga-Ectoplasma',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-06-05' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 2599,
  },
  {
    id: 'premium-mega-amphinobi',
    titleFr: 'Coffret Collection Premium Méga-Amphinobi-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-07-03' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 4999,
  },
  {
    id: 'prerelease-nuit-noire',
    titleFr: 'Boîtier Stratégies et Combats – Nuit Noire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 885540,
    window: { precision: 'day', date: '2026-07-04' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3000,
  },
  {
    id: 'tripack-nuit-noire',
    titleFr: 'Pack 3 boosters Méga-Évolution – Nuit Noire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-07-17' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1799,
  },
  {
    id: 'etb-nuit-noire',
    titleFr: 'Coffret Dresseur d’élite Méga-Évolution – Nuit Noire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 885542,
    window: { precision: 'day', date: '2026-07-17' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 5599,
  },
  {
    id: 'bundle-nuit-noire',
    titleFr: 'Lot de boosters Méga-Évolution – Nuit Noire',
    kind: 'sealed-product',
    market: 'FR',
    cardmarketProductId: 885539,
    window: { precision: 'day', date: '2026-07-17' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3599,
  },
  {
    id: 'collection-premiers-partenaires-serie-3',
    titleFr: 'Collection Illustration Premiers Partenaires – Série 3',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-08-07' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1999,
  },
  {
    id: 'duopack-zarude-2026',
    titleFr: 'Pack 2 boosters août 2026 – Duopack Zarude',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-08-07' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1199,
  },
  {
    id: 'pokebox-mega-puissances',
    titleFr: 'Boîte Méga Puissances – Méga-Zeraora, Méga-Darkrai ou Méga-Dracolosse',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-08-28' },
    status: 'released',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 2599,
  },
  {
    id: 'duopack-octobre-2026',
    titleFr: 'Pack 2 boosters octobre 2026 – Duopack Mimiqui, Ectoplasma et Marshadow',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-10-02' },
    status: 'announced',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1299,
  },
  {
    id: 'prerelease-regne-delta',
    titleFr: 'Boîtier Stratégies et Combats – Règne Delta',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-10-24' },
    status: 'announced',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3000,
  },
  {
    id: 'tripack-regne-delta',
    titleFr: 'Pack 3 boosters Méga-Évolution – Règne Delta',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 1799,
  },
  {
    id: 'etb-regne-delta',
    titleFr: 'Coffret Dresseur d’élite Méga-Évolution – Règne Delta',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 5599,
  },
  {
    id: 'bundle-regne-delta',
    titleFr: 'Lot de boosters Méga-Évolution – Règne Delta',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: POKECARDEX_2026_SOURCE,
    retailPriceCents: 3599,
  },
] as const satisfies readonly SealedReleaseV1[];
