import type { SealedReleaseV1 } from '@/lib/tcg-release-calendar';

/**
 * French-market editorial snapshot, version 1. Review each source and status
 * before updating; a date is never inferred from a marketplace listing.
 */
export const SEALED_RELEASES_V1 = [
  {
    id: 'pokemon-30th-anniversary-expansion',
    titleFr: '30ᵉ Anniversaire',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-09-16' },
    status: 'released',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/decouvrez-des-pokemon-legendaires-et-bien-plus-encore-dans-lextension-30-anniversaire-du-jcc-pokemon',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'mega-evolution-regne-delta',
    titleFr: 'Méga-Évolution – Règne Delta',
    kind: 'expansion',
    market: 'FR',
    window: { precision: 'day', date: '2026-11-06' },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/actualites/lextension-mega-evolution-regne-delta-du-jcc-pokemon-arrive-le-6-novembre-2026',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-autocollant-30e',
    titleFr: 'JCC Pokémon : Collection autocollant réajustable 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'blister-2-boosters-30e',
    titleFr: 'JCC Pokémon : blister de 2 boosters 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-ko-30e',
    titleFr: 'JCC Pokémon : Collection K.O. 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-poster-30e',
    titleFr: 'JCC Pokémon : Collection poster 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'coffrets-nymphali-amphinobi-30e',
    titleFr: 'JCC Pokémon : Coffret 30ᵉ Anniversaire – Nymphali-ex et Coffret 30ᵉ Anniversaire – Amphinobi-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'coffret-dresseur-elite-30e',
    titleFr: 'JCC Pokémon : Coffret Dresseur d’élite 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 3 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-premium-metamorph-30e',
    titleFr: 'JCC Pokémon : Collection Premium Métamorph 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-ultra-premium-journee-soiree-30e',
    titleFr: 'JCC Pokémon : Collection Ultra-Premium 30ᵉ Anniversaire – Journée et Soirée',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-figurine-mew-mewtwo-30e',
    titleFr: 'JCC Pokémon : Collection avec figurine 30ᵉ Anniversaire – Mew et Mewtwo',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'collection-classeur-30e',
    titleFr: 'JCC Pokémon : Collection classeur 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'lot-boosters-30e',
    titleFr: 'JCC Pokémon : lot de boosters 30ᵉ Anniversaire du JCC Pokémon',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'mini-boites-30e',
    titleFr: 'JCC Pokémon : Mini-boîtes 30ᵉ Anniversaire',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
  {
    id: 'decks-combat-mentali-noctali-30e',
    titleFr: 'JCC Pokémon : Deck Combat 30ᵉ Anniversaire – Mentali-ex et Deck Combat 30ᵉ Anniversaire – Noctali-ex',
    kind: 'sealed-product',
    market: 'FR',
    window: { precision: 'quarter', year: 2026, quarter: 4 },
    status: 'announced',
    source: {
      publisher: 'The Pokémon Company',
      url: 'https://www.pokemon.com/fr/news/jcc-pokemon-produits-30-anniversaire',
      verifiedAt: '2026-09-29',
    },
  },
] as const satisfies readonly SealedReleaseV1[];
